# syntax = docker/dockerfile-upstream:1.25.0-labs

# THIS FILE WAS AUTOMATICALLY GENERATED BY KRES, PLEASE DO NOT EDIT.
#
# Generated on 2026-07-30T12:18:06Z by kres 34f68df.

ARG TOOLCHAIN=scratch

FROM ghcr.io/siderolabs/talos-metal-agent-boot-assets:v1.13.6-agent-v0.1.6 AS assets

FROM ghcr.io/siderolabs/ca-certificates:v1.13.0 AS image-ca-certificates

FROM ghcr.io/siderolabs/fhs:v1.13.0 AS image-fhs

# runs markdownlint
FROM docker.io/oven/bun:1.3.14-alpine AS lint-markdown
WORKDIR /src
RUN bun i markdownlint-cli@0.49.0 sentences-per-line@0.5.3
COPY .markdownlint.json .
COPY ./AGENTS.md ./AGENTS.md
COPY ./CHANGELOG.md ./CHANGELOG.md
COPY ./CLAUDE.md ./CLAUDE.md
COPY ./GEMINI.md ./GEMINI.md
COPY ./README.md ./README.md
RUN bunx markdownlint --ignore "CHANGELOG.md" --ignore "**/node_modules/**" --ignore '**/hack/chglog/**' --rules markdownlint-sentences-per-line .

# collects proto specs
FROM scratch AS proto-specs
ADD api/specs/specs.proto /api/specs/

# source assets from ghcr.io/siderolabs/ipxe:v1.14.0-alpha.0-3-ge4d0113
FROM --platform=linux/amd64 ghcr.io/siderolabs/ipxe:v1.14.0-alpha.0-3-ge4d0113 AS source-assets-src-0

# source assets from ghcr.io/siderolabs/ipxe:v1.14.0-alpha.0-3-ge4d0113
FROM --platform=linux/arm64 ghcr.io/siderolabs/ipxe:v1.14.0-alpha.0-3-ge4d0113 AS source-assets-src-1

# base toolchain image
FROM --platform=${BUILDPLATFORM} ${TOOLCHAIN} AS toolchain
RUN apk --update --no-cache add bash build-base curl jq protoc protobuf-dev

# collects the source assets
FROM scratch AS source-assets
COPY --from=source-assets-src-0 /usr/libexec/ipxe.efi /internal/provider/ipxe/data/amd64/ipxe.efi
COPY --from=source-assets-src-0 /usr/libexec/snp.efi /internal/provider/ipxe/data/amd64/snp.efi
COPY --from=source-assets-src-0 /usr/libexec/kpxe/undionly.kpxe.bin /internal/provider/ipxe/data/amd64/kpxe/undionly.kpxe.bin
COPY --from=source-assets-src-0 /usr/libexec/kpxe/undionly.kpxe.zinfo /internal/provider/ipxe/data/amd64/kpxe/undionly.kpxe.zinfo
COPY --from=source-assets-src-1 /usr/libexec/ipxe.efi /internal/provider/ipxe/data/arm64/ipxe.efi
COPY --from=source-assets-src-1 /usr/libexec/snp.efi /internal/provider/ipxe/data/arm64/snp.efi

# build tools
FROM --platform=${BUILDPLATFORM} toolchain AS tools
ENV GO111MODULE=on
ARG CGO_ENABLED
ENV CGO_ENABLED=${CGO_ENABLED}
ARG GOTOOLCHAIN
ENV GOTOOLCHAIN=${GOTOOLCHAIN}
ARG GOEXPERIMENT
ENV GOEXPERIMENT=${GOEXPERIMENT}
ENV GOPATH=/go
ARG GOIMPORTS_VERSION
RUN --mount=type=cache,target=/root/.cache/go-build,id=omni-infra-provider-bare-metal/root/.cache/go-build --mount=type=cache,target=/go/pkg,id=omni-infra-provider-bare-metal/go/pkg go install golang.org/x/tools/cmd/goimports@v${GOIMPORTS_VERSION}
RUN mv /go/bin/goimports /bin
ARG GOMOCK_VERSION
RUN --mount=type=cache,target=/root/.cache/go-build,id=omni-infra-provider-bare-metal/root/.cache/go-build --mount=type=cache,target=/go/pkg,id=omni-infra-provider-bare-metal/go/pkg go install go.uber.org/mock/mockgen@v${GOMOCK_VERSION}
RUN mv /go/bin/mockgen /bin
ARG PROTOBUF_GO_VERSION
RUN --mount=type=cache,target=/root/.cache/go-build,id=omni-infra-provider-bare-metal/root/.cache/go-build --mount=type=cache,target=/go/pkg,id=omni-infra-provider-bare-metal/go/pkg go install google.golang.org/protobuf/cmd/protoc-gen-go@v${PROTOBUF_GO_VERSION}
RUN mv /go/bin/protoc-gen-go /bin
ARG GRPC_GO_VERSION
RUN --mount=type=cache,target=/root/.cache/go-build,id=omni-infra-provider-bare-metal/root/.cache/go-build --mount=type=cache,target=/go/pkg,id=omni-infra-provider-bare-metal/go/pkg go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v${GRPC_GO_VERSION}
RUN mv /go/bin/protoc-gen-go-grpc /bin
ARG GRPC_GATEWAY_VERSION
RUN --mount=type=cache,target=/root/.cache/go-build,id=omni-infra-provider-bare-metal/root/.cache/go-build --mount=type=cache,target=/go/pkg,id=omni-infra-provider-bare-metal/go/pkg go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v${GRPC_GATEWAY_VERSION}
RUN mv /go/bin/protoc-gen-grpc-gateway /bin
ARG VTPROTOBUF_VERSION
RUN --mount=type=cache,target=/root/.cache/go-build,id=omni-infra-provider-bare-metal/root/.cache/go-build --mount=type=cache,target=/go/pkg,id=omni-infra-provider-bare-metal/go/pkg go install github.com/planetscale/vtprotobuf/cmd/protoc-gen-go-vtproto@v${VTPROTOBUF_VERSION}
RUN mv /go/bin/protoc-gen-go-vtproto /bin
ARG DEEPCOPY_VERSION
RUN --mount=type=cache,target=/root/.cache/go-build,id=omni-infra-provider-bare-metal/root/.cache/go-build --mount=type=cache,target=/go/pkg,id=omni-infra-provider-bare-metal/go/pkg go install github.com/siderolabs/deep-copy@${DEEPCOPY_VERSION} \
	&& mv /go/bin/deep-copy /bin/deep-copy
ARG GOLANGCILINT_VERSION
RUN --mount=type=cache,target=/root/.cache/go-build,id=omni-infra-provider-bare-metal/root/.cache/go-build --mount=type=cache,target=/go/pkg,id=omni-infra-provider-bare-metal/go/pkg go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@${GOLANGCILINT_VERSION} \
	&& mv /go/bin/golangci-lint /bin/golangci-lint
RUN --mount=type=cache,target=/root/.cache/go-build,id=omni-infra-provider-bare-metal/root/.cache/go-build --mount=type=cache,target=/go/pkg,id=omni-infra-provider-bare-metal/go/pkg go install golang.org/x/vuln/cmd/govulncheck@latest \
	&& mv /go/bin/govulncheck /bin/govulncheck
ARG DIS_VULNCHECK_VERSION
RUN --mount=type=cache,target=/root/.cache/go-build,id=omni-infra-provider-bare-metal/root/.cache/go-build --mount=type=cache,target=/go/pkg,id=omni-infra-provider-bare-metal/go/pkg go install github.com/shanduur/dis-vulncheck@${DIS_VULNCHECK_VERSION} \
	&& mv /go/bin/dis-vulncheck /bin/dis-vulncheck
ARG GOFUMPT_VERSION
RUN go install mvdan.cc/gofumpt@${GOFUMPT_VERSION} \
	&& mv /go/bin/gofumpt /bin/gofumpt

# tools and sources
FROM tools AS base
WORKDIR /src
COPY go.mod go.mod
COPY go.sum go.sum
RUN cd .
RUN --mount=type=cache,target=/go/pkg,id=omni-infra-provider-bare-metal/go/pkg go mod download
RUN --mount=type=cache,target=/go/pkg,id=omni-infra-provider-bare-metal/go/pkg go mod verify
COPY ./api ./api
COPY ./cmd ./cmd
COPY ./internal ./internal
COPY --from=source-assets / ./
RUN --mount=type=cache,target=/go/pkg,id=omni-infra-provider-bare-metal/go/pkg go list -mod=readonly all >/dev/null

FROM tools AS embed-generate
ARG SHA
ARG TAG
WORKDIR /src
RUN mkdir -p internal/version/data && \
    echo -n ${SHA} > internal/version/data/sha && \
    echo -n ${TAG} > internal/version/data/tag

# runs protobuf compiler
FROM tools AS proto-compile
COPY --from=proto-specs / /
RUN protoc -I/api --go_out=paths=source_relative:/api --go-grpc_out=paths=source_relative:/api --go-vtproto_out=paths=source_relative:/api --go-vtproto_opt=features=marshal+unmarshal+size+equal+clone /api/specs/specs.proto
RUN rm /api/specs/specs.proto
RUN goimports -w -local github.com/siderolabs/omni-infra-provider-bare-metal /api
RUN gofumpt -w /api

# runs gofumpt
FROM base AS lint-gofumpt
RUN FILES="$(gofumpt -l .)" && test -z "${FILES}" || (echo -e "Source code is not formatted with 'gofumpt -w .':\n${FILES}"; exit 1)

# runs golangci-lint
FROM base AS lint-golangci-lint
WORKDIR /src
COPY .golangci.yml .
ENV GOGC=50
RUN --mount=type=cache,target=/root/.cache/go-build,id=omni-infra-provider-bare-metal/root/.cache/go-build --mount=type=cache,target=/root/.cache/golangci-lint,id=omni-infra-provider-bare-metal/root/.cache/golangci-lint,sharing=locked --mount=type=cache,target=/go/pkg,id=omni-infra-provider-bare-metal/go/pkg golangci-lint run --config .golangci.yml

# runs golangci-lint fmt
FROM base AS lint-golangci-lint-fmt-run
WORKDIR /src
COPY .golangci.yml .
ENV GOGC=50
RUN --mount=type=cache,target=/root/.cache/go-build,id=omni-infra-provider-bare-metal/root/.cache/go-build --mount=type=cache,target=/root/.cache/golangci-lint,id=omni-infra-provider-bare-metal/root/.cache/golangci-lint,sharing=locked --mount=type=cache,target=/go/pkg,id=omni-infra-provider-bare-metal/go/pkg golangci-lint fmt --config .golangci.yml
RUN --mount=type=cache,target=/root/.cache/go-build,id=omni-infra-provider-bare-metal/root/.cache/go-build --mount=type=cache,target=/root/.cache/golangci-lint,id=omni-infra-provider-bare-metal/root/.cache/golangci-lint,sharing=locked --mount=type=cache,target=/go/pkg,id=omni-infra-provider-bare-metal/go/pkg golangci-lint run --fix --issues-exit-code 0 --config .golangci.yml

# runs govulncheck
FROM base AS lint-govulncheck
WORKDIR /src
RUN --mount=type=cache,target=/root/.cache/go-build,id=omni-infra-provider-bare-metal/root/.cache/go-build --mount=type=cache,target=/go/pkg,id=omni-infra-provider-bare-metal/go/pkg dis-vulncheck -tool=false ./...

# runs unit-tests with race detector
FROM base AS unit-tests-race
WORKDIR /src
ARG TESTPKGS
RUN --mount=type=cache,target=/root/.cache/go-build,id=omni-infra-provider-bare-metal/root/.cache/go-build --mount=type=cache,target=/go/pkg,id=omni-infra-provider-bare-metal/go/pkg --mount=type=cache,target=/tmp,id=omni-infra-provider-bare-metal/tmp CGO_ENABLED=1 go test -race ${TESTPKGS}

# runs unit-tests
FROM base AS unit-tests-run
WORKDIR /src
ARG TESTPKGS
RUN --mount=type=cache,target=/root/.cache/go-build,id=omni-infra-provider-bare-metal/root/.cache/go-build --mount=type=cache,target=/go/pkg,id=omni-infra-provider-bare-metal/go/pkg --mount=type=cache,target=/tmp,id=omni-infra-provider-bare-metal/tmp go test -covermode=atomic -coverprofile=coverage.txt -coverpkg=${TESTPKGS} ${TESTPKGS}

FROM embed-generate AS embed-abbrev-generate
WORKDIR /src
ARG ABBREV_TAG
RUN echo -n 'undefined' > internal/version/data/sha && \
    echo -n ${ABBREV_TAG} > internal/version/data/tag

# clean golangci-lint fmt output
FROM scratch AS lint-golangci-lint-fmt
COPY --from=lint-golangci-lint-fmt-run /src .

FROM scratch AS unit-tests
COPY --from=unit-tests-run /src/coverage.txt /coverage-unit-tests.txt

# cleaned up specs and compiled versions
FROM scratch AS generate
COPY --from=proto-compile /api/ /api/
COPY --from=embed-abbrev-generate /src/internal/version internal/version

# builds provider-linux-amd64
FROM base AS provider-linux-amd64-build
COPY --from=generate / /
COPY --from=embed-generate / /
WORKDIR /src/cmd/provider
ARG GO_BUILDFLAGS
ARG GO_GCFLAGS
ARG GO_LDFLAGS
ARG VERSION_PKG="internal/version"
ARG SHA
ARG TAG
RUN --mount=type=cache,target=/root/.cache/go-build,id=omni-infra-provider-bare-metal/root/.cache/go-build --mount=type=cache,target=/go/pkg,id=omni-infra-provider-bare-metal/go/pkg GOARCH=amd64 GOOS=linux go build ${GO_BUILDFLAGS} -gcflags "${GO_GCFLAGS}" -ldflags "${GO_LDFLAGS} -X ${VERSION_PKG}.Name=provider -X ${VERSION_PKG}.SHA=${SHA} -X ${VERSION_PKG}.Tag=${TAG}" -o /provider-linux-amd64

# builds provider-linux-arm64
FROM base AS provider-linux-arm64-build
COPY --from=generate / /
COPY --from=embed-generate / /
WORKDIR /src/cmd/provider
ARG GO_BUILDFLAGS
ARG GO_GCFLAGS
ARG GO_LDFLAGS
ARG VERSION_PKG="internal/version"
ARG SHA
ARG TAG
RUN --mount=type=cache,target=/root/.cache/go-build,id=omni-infra-provider-bare-metal/root/.cache/go-build --mount=type=cache,target=/go/pkg,id=omni-infra-provider-bare-metal/go/pkg GOARCH=arm64 GOOS=linux go build ${GO_BUILDFLAGS} -gcflags "${GO_GCFLAGS}" -ldflags "${GO_LDFLAGS} -X ${VERSION_PKG}.Name=provider -X ${VERSION_PKG}.SHA=${SHA} -X ${VERSION_PKG}.Tag=${TAG}" -o /provider-linux-arm64

# builds qemu-up-linux-amd64
FROM base AS qemu-up-linux-amd64-build
COPY --from=generate / /
COPY --from=embed-generate / /
WORKDIR /src/cmd/qemu-up
ARG GO_BUILDFLAGS
ARG GO_GCFLAGS
ARG GO_LDFLAGS
ARG VERSION_PKG="internal/version"
ARG SHA
ARG TAG
RUN --mount=type=cache,target=/root/.cache/go-build,id=omni-infra-provider-bare-metal/root/.cache/go-build --mount=type=cache,target=/go/pkg,id=omni-infra-provider-bare-metal/go/pkg GOARCH=amd64 GOOS=linux go build ${GO_BUILDFLAGS} -gcflags "${GO_GCFLAGS}" -ldflags "${GO_LDFLAGS} -X ${VERSION_PKG}.Name=qemu-up -X ${VERSION_PKG}.SHA=${SHA} -X ${VERSION_PKG}.Tag=${TAG}" -o /qemu-up-linux-amd64

# builds qemu-up-linux-arm64
FROM base AS qemu-up-linux-arm64-build
COPY --from=generate / /
COPY --from=embed-generate / /
WORKDIR /src/cmd/qemu-up
ARG GO_BUILDFLAGS
ARG GO_GCFLAGS
ARG GO_LDFLAGS
ARG VERSION_PKG="internal/version"
ARG SHA
ARG TAG
RUN --mount=type=cache,target=/root/.cache/go-build,id=omni-infra-provider-bare-metal/root/.cache/go-build --mount=type=cache,target=/go/pkg,id=omni-infra-provider-bare-metal/go/pkg GOARCH=arm64 GOOS=linux go build ${GO_BUILDFLAGS} -gcflags "${GO_GCFLAGS}" -ldflags "${GO_LDFLAGS} -X ${VERSION_PKG}.Name=qemu-up -X ${VERSION_PKG}.SHA=${SHA} -X ${VERSION_PKG}.Tag=${TAG}" -o /qemu-up-linux-arm64

FROM scratch AS provider-linux-amd64
COPY --from=provider-linux-amd64-build /provider-linux-amd64 /provider-linux-amd64

FROM scratch AS provider-linux-arm64
COPY --from=provider-linux-arm64-build /provider-linux-arm64 /provider-linux-arm64

FROM scratch AS qemu-up-linux-amd64
COPY --from=qemu-up-linux-amd64-build /qemu-up-linux-amd64 /qemu-up-linux-amd64

FROM scratch AS qemu-up-linux-arm64
COPY --from=qemu-up-linux-arm64-build /qemu-up-linux-arm64 /qemu-up-linux-arm64

FROM provider-linux-${TARGETARCH} AS provider

FROM scratch AS provider-all
COPY --from=provider-linux-amd64 / /
COPY --from=provider-linux-arm64 / /

FROM qemu-up-linux-${TARGETARCH} AS qemu-up

FROM scratch AS qemu-up-all
COPY --from=qemu-up-linux-amd64 / /
COPY --from=qemu-up-linux-arm64 / /

FROM scratch AS image-provider
ARG TARGETARCH
COPY --from=provider provider-linux-${TARGETARCH} /provider
COPY --from=image-fhs / /
COPY --from=image-ca-certificates / /
COPY --from=assets / /assets
LABEL org.opencontainers.image.source=https://github.com/siderolabs/omni-infra-provider-bare-metal
ENTRYPOINT ["/provider"]

