// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: specs/specs.proto

package specs

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PowerState int32

const (
	PowerState_POWER_STATE_UNKNOWN PowerState = 0
	PowerState_POWER_STATE_OFF     PowerState = 1
	PowerState_POWER_STATE_ON      PowerState = 2
)

// Enum value maps for PowerState.
var (
	PowerState_name = map[int32]string{
		0: "POWER_STATE_UNKNOWN",
		1: "POWER_STATE_OFF",
		2: "POWER_STATE_ON",
	}
	PowerState_value = map[string]int32{
		"POWER_STATE_UNKNOWN": 0,
		"POWER_STATE_OFF":     1,
		"POWER_STATE_ON":      2,
	}
)

func (x PowerState) Enum() *PowerState {
	p := new(PowerState)
	*p = x
	return p
}

func (x PowerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PowerState) Descriptor() protoreflect.EnumDescriptor {
	return file_specs_specs_proto_enumTypes[0].Descriptor()
}

func (PowerState) Type() protoreflect.EnumType {
	return &file_specs_specs_proto_enumTypes[0]
}

func (x PowerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PowerState.Descriptor instead.
func (PowerState) EnumDescriptor() ([]byte, []int) {
	return file_specs_specs_proto_rawDescGZIP(), []int{0}
}

type PowerOperationSpec struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	LastPowerOperation   PowerState             `protobuf:"varint,1,opt,name=last_power_operation,json=lastPowerOperation,proto3,enum=baremetalproviderspecs.PowerState" json:"last_power_operation,omitempty"`
	LastPowerOnTimestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_power_on_timestamp,json=lastPowerOnTimestamp,proto3" json:"last_power_on_timestamp,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PowerOperationSpec) Reset() {
	*x = PowerOperationSpec{}
	mi := &file_specs_specs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PowerOperationSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerOperationSpec) ProtoMessage() {}

func (x *PowerOperationSpec) ProtoReflect() protoreflect.Message {
	mi := &file_specs_specs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerOperationSpec.ProtoReflect.Descriptor instead.
func (*PowerOperationSpec) Descriptor() ([]byte, []int) {
	return file_specs_specs_proto_rawDescGZIP(), []int{0}
}

func (x *PowerOperationSpec) GetLastPowerOperation() PowerState {
	if x != nil {
		return x.LastPowerOperation
	}
	return PowerState_POWER_STATE_UNKNOWN
}

func (x *PowerOperationSpec) GetLastPowerOnTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.LastPowerOnTimestamp
	}
	return nil
}

type BMCConfigurationSpec struct {
	state              protoimpl.MessageState     `protogen:"open.v1"`
	Ipmi               *BMCConfigurationSpec_IPMI `protobuf:"bytes,1,opt,name=ipmi,proto3" json:"ipmi,omitempty"`
	Api                *BMCConfigurationSpec_API  `protobuf:"bytes,2,opt,name=api,proto3" json:"api,omitempty"`
	ManuallyConfigured bool                       `protobuf:"varint,3,opt,name=manually_configured,json=manuallyConfigured,proto3" json:"manually_configured,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BMCConfigurationSpec) Reset() {
	*x = BMCConfigurationSpec{}
	mi := &file_specs_specs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BMCConfigurationSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BMCConfigurationSpec) ProtoMessage() {}

func (x *BMCConfigurationSpec) ProtoReflect() protoreflect.Message {
	mi := &file_specs_specs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BMCConfigurationSpec.ProtoReflect.Descriptor instead.
func (*BMCConfigurationSpec) Descriptor() ([]byte, []int) {
	return file_specs_specs_proto_rawDescGZIP(), []int{1}
}

func (x *BMCConfigurationSpec) GetIpmi() *BMCConfigurationSpec_IPMI {
	if x != nil {
		return x.Ipmi
	}
	return nil
}

func (x *BMCConfigurationSpec) GetApi() *BMCConfigurationSpec_API {
	if x != nil {
		return x.Api
	}
	return nil
}

func (x *BMCConfigurationSpec) GetManuallyConfigured() bool {
	if x != nil {
		return x.ManuallyConfigured
	}
	return false
}

type MachineStatusSpec struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentAccessible bool                   `protobuf:"varint,1,opt,name=agent_accessible,json=agentAccessible,proto3" json:"agent_accessible,omitempty"`
	PowerState      PowerState             `protobuf:"varint,2,opt,name=power_state,json=powerState,proto3,enum=baremetalproviderspecs.PowerState" json:"power_state,omitempty"`
	Initialized     bool                   `protobuf:"varint,4,opt,name=initialized,proto3" json:"initialized,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MachineStatusSpec) Reset() {
	*x = MachineStatusSpec{}
	mi := &file_specs_specs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineStatusSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineStatusSpec) ProtoMessage() {}

func (x *MachineStatusSpec) ProtoReflect() protoreflect.Message {
	mi := &file_specs_specs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineStatusSpec.ProtoReflect.Descriptor instead.
func (*MachineStatusSpec) Descriptor() ([]byte, []int) {
	return file_specs_specs_proto_rawDescGZIP(), []int{2}
}

func (x *MachineStatusSpec) GetAgentAccessible() bool {
	if x != nil {
		return x.AgentAccessible
	}
	return false
}

func (x *MachineStatusSpec) GetPowerState() PowerState {
	if x != nil {
		return x.PowerState
	}
	return PowerState_POWER_STATE_UNKNOWN
}

func (x *MachineStatusSpec) GetInitialized() bool {
	if x != nil {
		return x.Initialized
	}
	return false
}

type WipeStatusSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// LastWipeId is the ID of the last wipe operation that was performed on the machine.
	//
	// It is used to track if the machine needs to be wiped for an allocation.
	LastWipeId string `protobuf:"bytes,1,opt,name=last_wipe_id,json=lastWipeId,proto3" json:"last_wipe_id,omitempty"`
	// LastWipeInstallEventId is set to the same value of InfraMachine.InstallEventId field each time machine gets wiped.
	//
	// Using this, the provider is able to track the installation state of Talos on the machine. It does it by comparing this stored value
	// with the value of InfraMachine.InstallEventId field.
	//
	// If the value of InfraMachine.InstallEventId field is greater than the value of this field,
	// it means that Omni observed, after the wipe, at least one event indicating Talos is installed on that machine.
	LastWipeInstallEventId uint64 `protobuf:"varint,2,opt,name=last_wipe_install_event_id,json=lastWipeInstallEventId,proto3" json:"last_wipe_install_event_id,omitempty"`
	InitialWipeDone        bool   `protobuf:"varint,3,opt,name=initial_wipe_done,json=initialWipeDone,proto3" json:"initial_wipe_done,omitempty"`
	// WipedNodeUniqueToken contains the value of the node unique token used during the last node wipe.
	WipedNodeUniqueToken string `protobuf:"bytes,4,opt,name=wiped_node_unique_token,json=wipedNodeUniqueToken,proto3" json:"wiped_node_unique_token,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *WipeStatusSpec) Reset() {
	*x = WipeStatusSpec{}
	mi := &file_specs_specs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WipeStatusSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WipeStatusSpec) ProtoMessage() {}

func (x *WipeStatusSpec) ProtoReflect() protoreflect.Message {
	mi := &file_specs_specs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WipeStatusSpec.ProtoReflect.Descriptor instead.
func (*WipeStatusSpec) Descriptor() ([]byte, []int) {
	return file_specs_specs_proto_rawDescGZIP(), []int{3}
}

func (x *WipeStatusSpec) GetLastWipeId() string {
	if x != nil {
		return x.LastWipeId
	}
	return ""
}

func (x *WipeStatusSpec) GetLastWipeInstallEventId() uint64 {
	if x != nil {
		return x.LastWipeInstallEventId
	}
	return 0
}

func (x *WipeStatusSpec) GetInitialWipeDone() bool {
	if x != nil {
		return x.InitialWipeDone
	}
	return false
}

func (x *WipeStatusSpec) GetWipedNodeUniqueToken() string {
	if x != nil {
		return x.WipedNodeUniqueToken
	}
	return ""
}

type RebootStatusSpec struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	LastRebootId string                 `protobuf:"bytes,1,opt,name=last_reboot_id,json=lastRebootId,proto3" json:"last_reboot_id,omitempty"`
	// LastRebootTimestamp is the timestamp of the last reboot (or power on) of the machine.
	//
	// It is used to track the last reboot time of the machine, and to enforce the MinRebootInterval.
	LastRebootTimestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_reboot_timestamp,json=lastRebootTimestamp,proto3" json:"last_reboot_timestamp,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RebootStatusSpec) Reset() {
	*x = RebootStatusSpec{}
	mi := &file_specs_specs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebootStatusSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebootStatusSpec) ProtoMessage() {}

func (x *RebootStatusSpec) ProtoReflect() protoreflect.Message {
	mi := &file_specs_specs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebootStatusSpec.ProtoReflect.Descriptor instead.
func (*RebootStatusSpec) Descriptor() ([]byte, []int) {
	return file_specs_specs_proto_rawDescGZIP(), []int{4}
}

func (x *RebootStatusSpec) GetLastRebootId() string {
	if x != nil {
		return x.LastRebootId
	}
	return ""
}

func (x *RebootStatusSpec) GetLastRebootTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRebootTimestamp
	}
	return nil
}

type TLSConfigSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaCert        string                 `protobuf:"bytes,1,opt,name=ca_cert,json=caCert,proto3" json:"ca_cert,omitempty"`
	CaKey         string                 `protobuf:"bytes,2,opt,name=ca_key,json=caKey,proto3" json:"ca_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLSConfigSpec) Reset() {
	*x = TLSConfigSpec{}
	mi := &file_specs_specs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLSConfigSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSConfigSpec) ProtoMessage() {}

func (x *TLSConfigSpec) ProtoReflect() protoreflect.Message {
	mi := &file_specs_specs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSConfigSpec.ProtoReflect.Descriptor instead.
func (*TLSConfigSpec) Descriptor() ([]byte, []int) {
	return file_specs_specs_proto_rawDescGZIP(), []int{5}
}

func (x *TLSConfigSpec) GetCaCert() string {
	if x != nil {
		return x.CaCert
	}
	return ""
}

func (x *TLSConfigSpec) GetCaKey() string {
	if x != nil {
		return x.CaKey
	}
	return ""
}

type BMCConfigurationSpec_IPMI struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BMCConfigurationSpec_IPMI) Reset() {
	*x = BMCConfigurationSpec_IPMI{}
	mi := &file_specs_specs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BMCConfigurationSpec_IPMI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BMCConfigurationSpec_IPMI) ProtoMessage() {}

func (x *BMCConfigurationSpec_IPMI) ProtoReflect() protoreflect.Message {
	mi := &file_specs_specs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BMCConfigurationSpec_IPMI.ProtoReflect.Descriptor instead.
func (*BMCConfigurationSpec_IPMI) Descriptor() ([]byte, []int) {
	return file_specs_specs_proto_rawDescGZIP(), []int{1, 0}
}

func (x *BMCConfigurationSpec_IPMI) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *BMCConfigurationSpec_IPMI) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *BMCConfigurationSpec_IPMI) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BMCConfigurationSpec_IPMI) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type BMCConfigurationSpec_API struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BMCConfigurationSpec_API) Reset() {
	*x = BMCConfigurationSpec_API{}
	mi := &file_specs_specs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BMCConfigurationSpec_API) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BMCConfigurationSpec_API) ProtoMessage() {}

func (x *BMCConfigurationSpec_API) ProtoReflect() protoreflect.Message {
	mi := &file_specs_specs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BMCConfigurationSpec_API.ProtoReflect.Descriptor instead.
func (*BMCConfigurationSpec_API) Descriptor() ([]byte, []int) {
	return file_specs_specs_proto_rawDescGZIP(), []int{1, 1}
}

func (x *BMCConfigurationSpec_API) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_specs_specs_proto protoreflect.FileDescriptor

const file_specs_specs_proto_rawDesc = "" +
	"\n" +
	"\x11specs/specs.proto\x12\x16baremetalproviderspecs\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbd\x01\n" +
	"\x12PowerOperationSpec\x12T\n" +
	"\x14last_power_operation\x18\x01 \x01(\x0e2\".baremetalproviderspecs.PowerStateR\x12lastPowerOperation\x12Q\n" +
	"\x17last_power_on_timestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x14lastPowerOnTimestamp\"\xe1\x02\n" +
	"\x14BMCConfigurationSpec\x12E\n" +
	"\x04ipmi\x18\x01 \x01(\v21.baremetalproviderspecs.BMCConfigurationSpec.IPMIR\x04ipmi\x12B\n" +
	"\x03api\x18\x02 \x01(\v20.baremetalproviderspecs.BMCConfigurationSpec.APIR\x03api\x12/\n" +
	"\x13manually_configured\x18\x03 \x01(\bR\x12manuallyConfigured\x1al\n" +
	"\x04IPMI\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x1a\x1f\n" +
	"\x03API\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\xab\x01\n" +
	"\x11MachineStatusSpec\x12)\n" +
	"\x10agent_accessible\x18\x01 \x01(\bR\x0fagentAccessible\x12C\n" +
	"\vpower_state\x18\x02 \x01(\x0e2\".baremetalproviderspecs.PowerStateR\n" +
	"powerState\x12 \n" +
	"\vinitialized\x18\x04 \x01(\bR\vinitializedJ\x04\b\x03\x10\x04\"\xd1\x01\n" +
	"\x0eWipeStatusSpec\x12 \n" +
	"\flast_wipe_id\x18\x01 \x01(\tR\n" +
	"lastWipeId\x12:\n" +
	"\x1alast_wipe_install_event_id\x18\x02 \x01(\x04R\x16lastWipeInstallEventId\x12*\n" +
	"\x11initial_wipe_done\x18\x03 \x01(\bR\x0finitialWipeDone\x125\n" +
	"\x17wiped_node_unique_token\x18\x04 \x01(\tR\x14wipedNodeUniqueToken\"\x88\x01\n" +
	"\x10RebootStatusSpec\x12$\n" +
	"\x0elast_reboot_id\x18\x01 \x01(\tR\flastRebootId\x12N\n" +
	"\x15last_reboot_timestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x13lastRebootTimestamp\"?\n" +
	"\rTLSConfigSpec\x12\x17\n" +
	"\aca_cert\x18\x01 \x01(\tR\x06caCert\x12\x15\n" +
	"\x06ca_key\x18\x02 \x01(\tR\x05caKey*N\n" +
	"\n" +
	"PowerState\x12\x17\n" +
	"\x13POWER_STATE_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fPOWER_STATE_OFF\x10\x01\x12\x12\n" +
	"\x0ePOWER_STATE_ON\x10\x02B@Z>github.com/siderolabs/omni-infra-provider-bare-metal/api/specsb\x06proto3"

var (
	file_specs_specs_proto_rawDescOnce sync.Once
	file_specs_specs_proto_rawDescData []byte
)

func file_specs_specs_proto_rawDescGZIP() []byte {
	file_specs_specs_proto_rawDescOnce.Do(func() {
		file_specs_specs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_specs_specs_proto_rawDesc), len(file_specs_specs_proto_rawDesc)))
	})
	return file_specs_specs_proto_rawDescData
}

var file_specs_specs_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_specs_specs_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_specs_specs_proto_goTypes = []any{
	(PowerState)(0),                   // 0: baremetalproviderspecs.PowerState
	(*PowerOperationSpec)(nil),        // 1: baremetalproviderspecs.PowerOperationSpec
	(*BMCConfigurationSpec)(nil),      // 2: baremetalproviderspecs.BMCConfigurationSpec
	(*MachineStatusSpec)(nil),         // 3: baremetalproviderspecs.MachineStatusSpec
	(*WipeStatusSpec)(nil),            // 4: baremetalproviderspecs.WipeStatusSpec
	(*RebootStatusSpec)(nil),          // 5: baremetalproviderspecs.RebootStatusSpec
	(*TLSConfigSpec)(nil),             // 6: baremetalproviderspecs.TLSConfigSpec
	(*BMCConfigurationSpec_IPMI)(nil), // 7: baremetalproviderspecs.BMCConfigurationSpec.IPMI
	(*BMCConfigurationSpec_API)(nil),  // 8: baremetalproviderspecs.BMCConfigurationSpec.API
	(*timestamppb.Timestamp)(nil),     // 9: google.protobuf.Timestamp
}
var file_specs_specs_proto_depIdxs = []int32{
	0, // 0: baremetalproviderspecs.PowerOperationSpec.last_power_operation:type_name -> baremetalproviderspecs.PowerState
	9, // 1: baremetalproviderspecs.PowerOperationSpec.last_power_on_timestamp:type_name -> google.protobuf.Timestamp
	7, // 2: baremetalproviderspecs.BMCConfigurationSpec.ipmi:type_name -> baremetalproviderspecs.BMCConfigurationSpec.IPMI
	8, // 3: baremetalproviderspecs.BMCConfigurationSpec.api:type_name -> baremetalproviderspecs.BMCConfigurationSpec.API
	0, // 4: baremetalproviderspecs.MachineStatusSpec.power_state:type_name -> baremetalproviderspecs.PowerState
	9, // 5: baremetalproviderspecs.RebootStatusSpec.last_reboot_timestamp:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_specs_specs_proto_init() }
func file_specs_specs_proto_init() {
	if File_specs_specs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_specs_specs_proto_rawDesc), len(file_specs_specs_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_specs_specs_proto_goTypes,
		DependencyIndexes: file_specs_specs_proto_depIdxs,
		EnumInfos:         file_specs_specs_proto_enumTypes,
		MessageInfos:      file_specs_specs_proto_msgTypes,
	}.Build()
	File_specs_specs_proto = out.File
	file_specs_specs_proto_goTypes = nil
	file_specs_specs_proto_depIdxs = nil
}
